apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-provider-secret
type: Opaque
data:
  NEXT_PUBLIC_MANAGEMENT_API_URL: {{ .Values.secrets.provider.nextPublicManagementApiUrl | b64enc }}
  NEXT_PUBLIC_MANAGEMENT_API_KEY: {{ .Values.secrets.provider.nextPublicManagementApiKey | b64enc }}

  sovity.deployment.kind: {{ .Values.secrets.provider.sovityDeploymentKind | b64enc }}
  sovity.edc.fqdn.internal: {{ .Values.secrets.provider.sovityFqdnInternal | b64enc }}
  sovity.jdbc.url: {{ .Values.secrets.provider.sovityJdbcUrl | b64enc }}
  sovity.jdbc.user: {{ .Values.secrets.provider.sovityJdbcUser | b64enc }}
  sovity.jdbc.password: {{ .Values.secrets.provider.sovityJdbcPassword | b64enc }}
  sovity.management.api.iam.kind: {{ .Values.secrets.provider.sovityManagementApiIamKind | b64enc }}
  edc.api.auth.key: {{ .Values.secrets.provider.edcApiAuthKey | b64enc }}
  sovity.edc.title: {{ .Values.secrets.provider.sovityEdcTitle | b64enc }}
  sovity.edc.description: {{ .Values.secrets.provider.sovityEdcDescription | b64enc }}
  sovity.edc.maintainer.name: {{ .Values.secrets.provider.sovityEdcMaintainerName | b64enc }}
  sovity.edc.maintainer.url: {{ .Values.secrets.provider.sovityEdcMaintainerUrl | b64enc }}
  sovity.edc.curator.name: {{ .Values.secrets.provider.sovityEdcCuratorName | b64enc }}
  sovity.edc.curator.url: {{ .Values.secrets.provider.sovityEdcCuratorUrl | b64enc }}
  {{- if .Values.debug.remoteDebug }}
  REMOTE_DEBUG_BIND: {{ .Values.secrets.provider.remoteDebugBind | b64enc }}
  {{- end }}
  sovity.edc.ui.preconfigured.counterparties: {{ .Values.secrets.provider.sovityEdcUiPreconfiguredCounterparties | b64enc }}
  sovity.edc.fqdn.public: {{ .Values.secrets.provider.sovityFqdnPublic | b64enc }}
  edc.dsp.callback.address: {{ .Values.secrets.provider.edcDspCallbackAddress | b64enc }}
  sovity.dataspace.kind: {{ .Values.secrets.provider.sovityDataspaceKind | b64enc }}
  edc.participant.id: {{ .Values.secrets.provider.edcParticipantId | b64enc }}
  sovity.http.protocol: {{ .Values.secrets.provider.sovityHttpProtocol | b64enc }}
  sovity.print.config: {{ .Values.secrets.provider.sovityPrintConfig | b64enc }}
  sovity.logging.level: {{ .Values.secrets.provider.sovityLoggingLevel | b64enc }}