apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
type: Opaque
data:
  NEXT_PUBLIC_MANAGEMENT_API_URL: {{ .Values.secrets.connector.nextPublicManagementApiUrl | b64enc }}
  NEXT_PUBLIC_MANAGEMENT_API_KEY: {{ .Values.secrets.connector.nextPublicManagementApiKey | b64enc }}

  sovity.deployment.kind: {{ .Values.secrets.connector.sovityDeploymentKind | b64enc }}
  sovity.edc.fqdn.internal: {{ .Values.secrets.connector.sovityFqdnInternal | b64enc }}
  sovity.jdbc.url: {{ .Values.secrets.connector.sovityJdbcUrl | b64enc }}
  sovity.jdbc.user: {{ .Values.secrets.connector.sovityJdbcUser | b64enc }}
  sovity.jdbc.password: {{ .Values.secrets.connector.sovityJdbcPassword | b64enc }}
  sovity.management.api.iam.kind: {{ .Values.secrets.connector.sovityManagementApiIamKind | b64enc }}
  edc.api.auth.key: {{ .Values.secrets.connector.edcApiAuthKey | b64enc }}
  sovity.edc.title: {{ .Values.secrets.connector.sovityEdcTitle | b64enc }}
  sovity.edc.description: {{ .Values.secrets.connector.sovityEdcDescription | b64enc }}
  sovity.edc.maintainer.name: {{ .Values.secrets.connector.sovityEdcMaintainerName | b64enc }}
  sovity.edc.maintainer.url: {{ .Values.secrets.connector.sovityEdcMaintainerUrl | b64enc }}
  sovity.edc.curator.name: {{ .Values.secrets.connector.sovityEdcCuratorName | b64enc }}
  sovity.edc.curator.url: {{ .Values.secrets.connector.sovityEdcCuratorUrl | b64enc }}
  {{- if .Values.debug.remoteDebug }}
  REMOTE_DEBUG_BIND: {{ .Values.secrets.connector.remoteDebugBind | b64enc }}
  {{- end }}
  sovity.edc.ui.preconfigured.counterparties: {{ .Values.secrets.connector.sovityEdcUiPreconfiguredCounterparties | b64enc }}
  sovity.edc.fqdn.public: {{ .Values.secrets.connector.sovityFqdnPublic | b64enc }}
  edc.dsp.callback.address: {{ .Values.secrets.connector.edcDspCallbackAddress | b64enc }}
  sovity.dataspace.kind: {{ .Values.secrets.connector.sovityDataspaceKind | b64enc }}
  edc.participant.id: {{ .Values.secrets.connector.edcParticipantId | b64enc }}
  sovity.http.protocol: {{ .Values.secrets.connector.sovityHttpProtocol | b64enc }}
  sovity.print.config: {{ .Values.secrets.connector.sovityPrintConfig | b64enc }}
  sovity.logging.level: {{ .Values.secrets.connector.sovityLoggingLevel | b64enc }}