apiVersion: v1
kind: Secret
metadata:
  name: postgres-provider-secret
type: Opaque
stringData:
  # See the consumer equivalent. Must match secrets.provider.sovityJdbcPassword.
  POSTGRES_PASSWORD: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | quote }}
